### PR TITLE
Vision registry successfully added. Corrections in birth registry. 

### PR DESCRIPTION
**Pull request by shanmukhasampath**
This is for issue #156 

Vision registry is properly mapped except for visual field diameter columns.

Visual field diameter (VFD) columns `OHALK` and `VHALK` have only non-standard codes in `FGVisitType` vocabulary but do not have standard code to map to.
 
All tests PASS.

### CODE REVIEW

**Comment by javier-gracia-tabuenca-tuni** [comment]
looks good, can we have the documentation also, to see if the code match the specs ??
do i understand correct that, the measurement don't have a standard concept ??

**Comment by shanmukhasampath** [comment]
Hi Javier, I am not sure I understand this "code match the specs"

Yes, the measurement of visual field diameter is something that is not used any standard vocabulary. There is no standard code to capture the measurement from vision registry. So, I introduced two non-standard measurement codes with the hope that this may change in future.

Yes, I can make a new issue of updating Vision documentation

**Comment by shanmukhasampath** [comment]
Hi Javier, I have pushed all the changes we talked about regarding mapping codes. Now there is no separate vision to condition occurrence sql but rather will go through the STEM table.

**Comment by javier-gracia-tabuenca-tuni** [comment]
add to documentation 
- vision table description to page Appendix > Source Tables
- duration of the birth and vision registers in the mermade plot in Appendix > Registers time duration

**Comment by shanmukhasampath** [comment]
> add to documentation
> 
> * vision table description to page Appendix > Source Tables
> * duration of the birth and vision registers in the mermade plot in Appendix > Registers time duration

Hi Javier, I have added the documentation for both.

**Pull request merged**
